DROP TABLE BorrowingRecords CASCADE CONSTRAINTS;
DROP TABLE Books CASCADE CONSTRAINTS;
DROP TABLE Students CASCADE CONSTRAINTS;
DROP TABLE BookTypes CASCADE CONSTRAINTS; 
DROP TABLE Penalties CASCADE CONSTRAINTS; 
DROP TABLE NotificationLogs CASCADE CONSTRAINTS; 
DROP TABLE AuditTrail CASCADE CONSTRAINTS;